### PR TITLE
Update AIS-06-M1 to have the same info as the published CAM Catalog v1.0

### PR DESCRIPTION
**Pull request by mosi-k-platt**
Added metricDescription, primaryControlID, relatedControlID, rules, and implementationGuidelines to AIS-06-M1. Kept fields in the same order as the published CAM catalog as much as possible. 

Questions:
1. Should relatedControlID values be listed on the same line and comma separated or should they listed on individual line breaks? 
2. Should the paragraphs in rules be combined onto 1 line or listed on individual line breaks? 
3. Same question for implementationGuidelines.

Also changed "metricChrontabExample" to "metricCrontabExample" (removed letter h typo)

### CODE REVIEW

**Comment by pritikin** [comment]
but 'chronology'... drat! thanks for fixing that and even calling it a typo. :)

**Comment by pritikin** [comment]
I think using newlines for the relatedControlIDs works well because then yaml interpreters generate a json struct that looks easier to parse:

```
relatedControlID: 
  - DCS-06
  - GRC-05
```
becomes:
```
{
  "relatedControlID": [
    "DCS-06",
    "GRC-05"
  ]
}
```

rather than 

```
relatedControlID: DCS-06, RC-05
{
  "relatedControlID": "DCS-06, RC-05"
}
```

(Unless there is an easy way to parse the latter. shrug. not my area).

**Comment by pritikin** [comment]
Rules and implementation guidelines are for human readability. I'd do them as one big string (e.g. on a single line without paragraph breaks). 

A note on these: it looks like the v1.0pdf metric catalog includes editorialized versions of the strings. If we're just cut/pasting we should pull from there as the current source of truth.

**Comment by mosi-k-platt** [comment]
> Rules and implementation guidelines are for human readability. I'd do them as one big string (e.g. on a single line without paragraph breaks).
> 
> A note on these: it looks like the v1.0pdf metric catalog includes editorialized versions of the strings. If we're just cut/pasting we should pull from there as the current source of truth.

@pritikin There was an extra paragraph in the Google Sheet version of rules for AIS-06-M1 that was not included in v1 of the catalog. I'm not sure when that paragraph got added, but since the Google Sheet was updated after catalog v1 was published, I was using that as the source of truth. I will update the PR for rules and implementation guidelines to be one big string.

**Comment by mosi-k-platt** [comment]
@pritikin I changed the rules & implementation guidelines to one big string

**Review by pritikin — APPROVED** [review]

**Comment by pritikin** [comment]
hmm.

I ok’d and merged the pull request. figured it was better to keep things moving than to wait until you had more diffs for the other metrics. I guess i could have waited. 

- max

**Pull request merged**
